export const ADD_GOOD_CART = "ADD_GOOD_CART";
export const GET_GOOD_NUMBER = "GET_GOOD_NUMBER";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
